################################################################################
# 
# NEOS: Makefile - HLT subsystem makefile 
#
# Copyright(c) 2009 MDS Technology Co.,Ltd. 
# All right reserved
#
# This software contains confidential information of MDS Technology Co.,Ltd.
# and unauthorized distribution of this software, or any portion of it, are
# prohibited.
# 
# Brief history
# -------------
# 2008.09.12, Jaehyung Jang: created.
#
################################################################################

ROOT = ..
# include the build rules
include $(ROOT)/make/rules.HLT.mk

